services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teacher_coop_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  meilisearch:
    image: getmeili/meilisearch:v1.53.1
    environment:
      MEILI_MASTER_KEY: masterkey
      MEILI_ENV: development
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

  s3mock:
    image: adobe/s3mock:5.2.3
    environment:
      COM_ADOBE_TESTING_S3MOCK_STORE_REGION: fr-par
      COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS: teachercoop
      COM_ADOBE_TESTING_S3MOCK_STORE_ROOT: /s3mockroot
      COM_ADOBE_TESTING_S3MOCK_STORE_RETAIN_FILES_ON_EXIT: "true"
    ports:
      - "9090:9090"
      - "9191:9191"
    volumes:
      - s3mock_data:/s3mockroot

volumes:
  postgres_data:
  meilisearch_data:
  tei_data:
  s3mock_data:
