services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
      PGTZ: UTC
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MASTER_KEY: ${MASTER_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

volumes:
  postgres_data:
  meilisearch_data:
