import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :teacher_coop, TeacherCoopWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl is disabled here because Traefik terminates the SSL connection
# in front of this app; the app itself only serves plain HTTP.
# config :teacher_coop, TeacherCoopWeb.Endpoint,
#   force_ssl: [
#     rewrite_on: [:x_forwarded_proto],
#     exclude: [
#       # paths: ["/health"],
#       hosts: ["localhost", "127.0.0.1"]
#     ]
#   ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
